services:
  pgvector:
    image: docker.io/ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: evolvai
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./src/main/sql/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
      - ./src/main/sql/init_adm_tables.sql:/docker-entrypoint-initdb.d/init_adm_tables.sql

  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    mem_limit: 20g
    cpus: 6
    environment:
      - OLLAMA_MODELS=phi3:mini

  ollama-init:
    image: docker.io/curlimages/curl
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
        until curl -s http://ollama:11434/; do sleep 2; done;
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"phi3:mini\"}'
      "
    volumes:
      - ollama_data:/root/.ollama
    restart: "no"

volumes:
  pgvector_data:
  ollama_data: