# Stage de build
FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY .m2 /root/.m2
COPY . .

RUN mvn -B -f pom.xml clean install -DskipTests

# Stage de runtime con glibc (basado en Debian, NO alpine ni slim)
FROM eclipse-temurin:21-jre

# Asegura presencia de dynamic linker
RUN apt-get update && apt-get install -y libc6 libstdc++6 && rm -rf /var/lib/apt/lists/*

# Copia el jar
COPY --from=builder /app/rag/target/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
