
services:

  pgvector:
    extends:
      file: ./rag/docker-compose.yml
      service: pgvector

  ollama:
    extends:
      file: ./rag/docker-compose.yml
      service: ollama

  ollama-init:
    extends:
      file: ./rag/docker-compose.yml
      service: ollama-init

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "80"
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - maven-repo:/root/.m2
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - ./rag/.env
    depends_on:
      pgvector:
        condition: service_healthy
      ollama:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully

volumes:
  pgvector-data:
  ollama-data:
  maven-repo:
