FROM node:18-alpine AS builder

WORKDIR /app

COPY web-app/package*.json ./
COPY web-app/vite.config.js ./
COPY web-app/ ./

RUN npm install
RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
