rag:
  embedding:
    pgvector:
      host: pgvector
    ollama:
      base-url: http://ollama:11434
  llm:
    ollama:
      base-url: http://ollama:11434

spring:
  datasource:
    url: jdbc:postgresql://pgvector:5432/evolvai

# Logging detallado
logging:
  level:
    io.micrometer: INFO
    org.springframework.boot.actuate: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"  # Habilita endpoints clave
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      dynatrace:
        enabled: true
        api-token: dummy-token   # Poné cualquier string para testeo
        uri: http://localhost:14499/api/v2/metrics/ingest # O el que tengas apuntando a WireMock o Dynatrace
        device-id: evolvai-dev
        technology-type: spring-boot
      prometheus:
        enabled: true
