@startuml
package "org.shark.evolvai.chathistory.adapter.out" {
    [ChatHistoryEntity] <<Entity>>
    [ChatHistoryJpaRepository] <<Repository>>
    [JpaChatHistoryRepository] <<Component>>
}

package "org.shark.evolvai.chathistory.port.output" {
    [ChatHistoryRepository] <<Interface>>
}

[JpaChatHistoryRepository] ..|> [ChatHistoryRepository]
[JpaChatHistoryRepository] --> [ChatHistoryJpaRepository]
[ChatHistoryJpaRepository] --> [ChatHistoryEntity]

package "org.shark.evolvai.embedding" {
    [EmbeddingService] <<Component>>
    [EmbeddingModel] <<Interface>>
}

[EmbeddingService] ..|> [EmbeddingModel]

package "org.shark.evolvai.inference" {
    [InferenceService] <<Component>>
}

[InferenceService] --> [EmbeddingService]

package "org.shark.evolvai.llm" {
    [LlmService] <<Component>>
}

[InferenceService] --> [LlmService]
@enduml