version: '3.8'

services:

  pgvector:
    image: ankane/pgvector
    container_name: evolvai_pgvector
    restart: always
    environment:
      POSTGRES_DB: evolvai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/sql/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=phi3:mini
      - OLLAMA_DEBUG=INFO
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama-init:
    image: curlimages/curl:latest
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Esperando a que Ollama esté listo...';
      sleep 5;
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"phi3:mini\"}' -H 'Content-Type: application/json';
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"nomic-embed-text\"}' -H 'Content-Type: application/json';
      echo 'Modelos phi3:mini y nomic-embed-text descargados';
      "

    restart: "no"

volumes:
  pgvector_data:
  ollama-data:
