version: "3.9"

services:
  evolvai-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: evolvai-app
    ports:
      - "8080:8080"
    depends_on:
      - pgvector
      - ollama
    restart: unless-stopped
