services:

  pgvector:
    image: docker.io/ankane/pgvector
    container_name: evolvai_pgvector
    restart: always
    environment:
      POSTGRES_DB: evolvai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/sql/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -sf http://localhost:11434/api/tags | grep 'phi3:mini'" ]
      interval: 10s
      timeout: 5s
      retries: 20

  rag-ollama-init:
    image: curlimages/curl:latest
    entrypoint: >
      /bin/sh -c "
      until curl -s http://ollama:11434; do
        echo 'Esperando a que Ollama esté listo...';
        sleep 2;
      done;
      echo 'Ollama listo, descargando modelos...';
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"phi3:mini\"}' -H 'Content-Type: application/json';
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"nomic-embed-text\"}' -H 'Content-Type: application/json';
      echo 'Modelos phi3:mini y nomic-embed-text descargados';
      "
    depends_on:
      - ollama



  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=phi3:mini
      - OLLAMA_DEBUG=INFO
      - OLLAMA_LLM_LIBRARY=cpu
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:11434" ]
      interval: 15s
      timeout: 10s
      retries: 10


volumes:
  ollama-data:
  pgvector-data:

