name: rag and pre-parser build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '**.txt'
      - '**.puml'
      - '.gitignore'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '**.txt'
      - '**.puml'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: rag compile
        working-directory: rag
        run: mvn clean install

      - name: pre-parser compile
        working-directory: preparser
        run: mvn clean install
